services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501"
    environment:
      - FQDN=${SERVICE_FQDN_API}
      - PORT=8501
    container_name: streamlit-demo123
    working_dir: /app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
