services:
  streamlit-app:
    image: python:3.12-slim
    container_name: streamlit-demo123
    restart: unless-stopped
    environment:
      STREAMLIT_SERVER_PORT: '8501'
      STREAMLIT_SERVER_ADDRESS: '0.0.0.0'
      COOLIFY_RESOURCE_UUID: demo123
      COOLIFY_CONTAINER_NAME: streamlit-demo123
      COOLIFY_URL: 'https://streamlit-demo123.loveforbags.in'
      COOLIFY_FQDN: streamlit-demo123.loveforbags.in
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    expose:
      - "8501"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - traefik.enable=true
      - "traefik.http.routers.streamlit.rule=Host(`streamlit-demo123.loveforbags.in`)"
      - "traefik.http.routers.streamlit.entrypoints=websecure"
      - "traefik.http.routers.streamlit.tls.certresolver=letsencrypt"
      - "traefik.http.services.streamlit.loadbalancer.server.port=8501"
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.serviceId=42
      - coolify.type=service
      - coolify.name=streamlit-demo123
      - coolify.resourceName=streamlit-demo123
      - coolify.projectName=my-demo-project
      - coolify.serviceName=streamlit
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - coolify.service.subId=42
      - coolify.service.subType=application
      - coolify.service.subName=streamlit
      - caddy_ingress_network=coolify

    networks:
      - coolify

networks:
  coolify:
    external: true
